# Use a Gradle image to build the application
FROM gradle:jdk21 as builder
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon

# Use OpenJDK image to run the application
FROM openjdk:21-jre-slim
EXPOSE 8080
COPY --from=builder /home/gradle/src/build/libs/*.jar /app/application.jar
WORKDIR /app
CMD ["java", "-jar", "application.jar"]
