micronaut:
  application:
    name: todo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: 'com.todo'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true








