micronaut:
  application:
    name: todo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: 'com.example.*'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update